---
# set_ntp_servers_for_chrony/tasks/main.yml

- name: 'Load variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Remove /etc/chrony.d/opensuse.conf'
  file:
    path: '/etc/chrony.d/opensuse.conf'
    state: 'absent'
  notify:
    - 'Restart chrony service'

- name: "Create directory {{ path_to_chrony_d_directory }} on Debian"
  file:
    path: "{{ path_to_chrony_d_directory }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: 'ansible_distribution == "Debian"'

- name: 'Create configuration file upstream_servers.conf for chrony'
  template:
    src: 'chrony.d_upstream_servers.conf.j2'
    dest: "{{ path_to_chrony_d_directory }}/upstream_servers.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart chrony service'

- name: 'Create {{ path_to_chrony_conf }} on Debian'
  template:
    src: 'Debian/etc_chrony.conf.j2'
    dest: "{{ path_to_chrony_conf }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'ansible_distribution == "Debian"'
  notify:
    - 'Restart chrony service'

- name: 'Enable and start chrony service'
  service:
    name: "{{ chrony_service }}"
    state: 'started'
    enabled: 'true'
